# -*- coding: utf-8 -*-
"""Suplemento de clasificacion de generos.
Cubre autores ausentes de generos_biblioteca.md y libros con autor desconocido.
Claves AUTOR_SUP: norm(autor) = minuscula, sin acentos, alfanumerico+espacio.
Claves TITULO_SUP: slug del archivo (sin .md).
Codigos: ECON MARX FILO CRIT PSIC ANTR HIST CARI RAZA FEMI ANAR ECOL GEOP TECH LITE CIEN MANGA
"""

AUTOR_SUP = {
    "enrique dussel": ["FILO", "RAZA"],
    "robert greene": ["FILO"],
    "elizabeth s d engelhardt": ["FEMI", "HIST"],
    "george ciccariello maher": ["ANAR"],
    "francis spufford": ["LITE"],
    "david mcnally": ["MARX"],
    "john cavanagh": ["ECON"],
    "hassan fathy": ["ANTR", "ECOL"],
    "ernst bloch": ["FILO", "CRIT"],
    "marc fleurbaey": ["ECON"],
    "rodrigo nunes": ["CRIT", "GEOP"],
    "zachary zane": ["FEMI"],
    "santiago armesilla conde": ["ECON"],
    "roberto fernandez retamar": ["CARI", "RAZA"],
    "jackie wang": ["RAZA", "ANAR"],
    "umberto eco eco umberto": ["CRIT", "FILO"],
    "fyodor dostoevsky": ["LITE"],
    "immanuel kant": ["FILO"],
    "arnold august": ["CARI", "GEOP"],
    "peter fleming": ["CRIT"],
    "james r akerman": ["TECH"],
    "mijail bakunin": ["ANAR"],
    "zak cope": ["GEOP", "MARX"],
    "bruno latour": ["CIEN", "ECOL"],
    "elizabeth a povinelli": ["ANTR", "RAZA"],
    "shel silverstein": ["LITE"],
    "leonel fernandez": ["CARI"],
    "david jimenez": ["LITE"],
    "el mundo como yo lo veo": ["CIEN"],
    "michel foucault": ["FILO", "CRIT"],
    "saint exupery": ["LITE"],
    "simone de beauvoir": ["FEMI", "FILO"],
    "robert chapman": ["CRIT"],
    "1984": ["CARI", "RAZA"],
    "georges bataille": ["FILO", "LITE"],
    "nicos poulantzas": ["MARX", "CRIT"],
    "georg wilhelm friedrich hegel": ["FILO"],
    "chuck palahniuk": ["LITE"],
    "1883": ["FILO"],
    "georgio agamben": ["FILO", "CRIT"],
    "giorgio agamben": ["FILO", "CRIT"],
    "v f cordova": ["FILO", "RAZA"],
    "pedro ross": ["CARI", "MARX"],
    "thich nhat hanh": ["FILO"],
    "terry eagleton": ["CRIT"],
    "darian leader judy groves": ["PSIC"],
    "angela nagle": ["CRIT", "TECH"],
    "pasour e c jr randal r rucker": ["ECON"],
    "acharya s": ["FILO"],
    "horacio quiroga": ["LITE"],
    "peter linebaugh": ["HIST", "RAZA"],
    "peter linebaugh marcus rediker": ["HIST", "RAZA"],
    "ana valero heredia": ["FEMI"],
    "bernardo moreno jimenez": ["FEMI", "HIST"],
    "micha frazer carroll": ["CRIT", "FEMI"],
    "enrique kramer": ["HIST", "FEMI"],
    "oswald de andrade": ["LITE", "RAZA"],
    "jerome ch en": ["MARX", "GEOP"],
    "slavoj zizek nicholas abercrombie etc": ["CRIT"],
    "ronald e purser": ["CRIT"],
    "marco aurelio": ["FILO"],
    "david saavedra": ["HIST", "GEOP"],
    "david saavedra david saavedra": ["HIST", "GEOP"],
    "martin caparro": ["LITE", "HIST"],
    "achille mbembe": ["RAZA", "CRIT"],
    "harlan ellison": ["LITE"],
    "david delgado": ["RAZA", "CIEN"],
    "virginia woolf": ["LITE", "FEMI"],
    "freire paulo": ["RAZA", "CRIT"],
    "jane austen": ["LITE"],
    "albert einstein": ["CIEN"],
    "alejandra pizarnik": ["LITE"],
    "peter sedgwick": ["CRIT", "PSIC"],
    "samuel p huntington": ["GEOP", "RAZA"],
    "martin nicolaus": ["MARX"],
    "paolo virno": ["MARX", "CRIT"],
    "gilles deleuze": ["FILO"],
    "gustavo gutierrez": ["FILO", "RAZA"],
    "joel black": ["CRIT", "LITE"],
    "george hawley": ["GEOP", "CRIT"],
    "rick rubin": ["FILO"],
    "dividing hispaniola": ["CARI", "RAZA"],
    "ilan pappe": ["GEOP", "HIST"],
    "philip s gorski": ["GEOP", "RAZA"],
    "william seabrook": ["CARI", "LITE"],
    "michael waters": ["FEMI", "HIST"],
    "jean francois lyotard": ["FILO", "CRIT"],
    "alf hornborg": ["ECOL", "ANTR"],
    "w b bland": ["MARX"],
    "nikolaj petrovic smelev": ["ECON", "MARX"],
    "martin hagglund": ["FILO"],
    "nelson mandela": ["RAZA", "HIST"],
    "paul kivel": ["RAZA"],
    "ruth frankenberg": ["RAZA", "FEMI"],
    "roxanne dunbar ortiz": ["HIST", "RAZA"],
}

# Libros con autor = "?" -> clasificar por slug del archivo
TITULO_SUP = {
    "argumentos-y-teorias-aproximacion-ala-espistemologia": ["CIEN"],
    "bad-gays-a-homosexual-history": ["FEMI", "HIST"],
    "biografia-de-un-cimarron": ["CARI", "RAZA", "LITE"],
    "capital-and-imperialism-theory-history-and-the-present": ["MARX", "GEOP"],
    "charged-how-the-police-try-to-suppress-protest": ["ANAR"],
    "china-o-socialismo-do-seculo-xxi": ["MARX", "GEOP"],
    "classical-econophysics": ["MARX", "TECH"],
    "constellations-of-care-anarcha-feminism-in-practice": ["ANAR", "FEMI"],
    "critical-race-theory-the-key-writings-that-formed-the-movement": ["RAZA"],
    "democracias-asediadas-golpes-de-estado-en-america-latina-siglos-xx-y-xxi": ["GEOP"],
    "economia": ["ECON"],
    "el-amanecer-de-todo-una-nueva-historia-de-la-humanidad": ["ANTR", "HIST"],
    "el-anti-edipo-capitalismo-y-esquizofrenia": ["FILO", "PSIC"],
    "energy-and-the-wealth-of-nations-an-introduction-to-biophysical-economics": ["ECOL", "ECON"],
    "from-columbus-to-castro-the-history-of-the-caribbean-1492-1969": ["CARI", "RAZA"],
    "futbol-y-politica-conversaciones-desde-la-izquierda": ["CRIT"],
    "hegemony-and-socialist-strategy-towards-a-radical-democratic-politics": ["CRIT", "MARX"],
    "las-figuras-retoricas-en-el-rap-espanol-del-siglo-xxi": ["LITE"],
    "lobo-estepario": ["LITE"],
    "los-guardianes-de-la-libertad": ["TECH", "GEOP"],
    "manifiesto-del-partido-comunista": ["MARX"],
    "para-leer-al-pato-donald": ["CRIT"],
    "que-es-la-filosofia": ["FILO"],
    "reactionary-democracy-how-racism-and-the-populist-far-right-became-mainstream": ["RAZA", "GEOP"],
    "readings-in-ancient-greek-philosophy-from-thales-to-aristotle": ["FILO"],
    "the-authoritarian-personality": ["CRIT", "PSIC"],
    "the-colour-of-democracy-racism-in-canadian-society": ["RAZA"],
    "the-ecological-rift-capitalism-s-war-on-the-earth": ["ECOL", "MARX"],
    "the-people-s-republic-of-walmart-how-the-world-s-biggest-corporations-are-laying": ["TECH", "MARX"],
    "the-people-s-republic-of-walmart": ["TECH", "MARX"],
    "dialectica-de-la-ilustracion": ["CRIT", "FILO"],
    "mula-cimarrona-no-soy-el-monstruo-que-os-habla": ["RAZA", "LITE"],
    "towards-a-new-socialism": ["MARX", "TECH"],
    "wage-labour-and-capital-value-price-and-profit": ["MARX"],
    "why-nations-fail": ["ECON", "HIST"],
}
